apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  parentRefs:
    - kind: Gateway
      name: avelin-gateway
      namespace: infra
  hostnames:
    - argocd.admin.avelin.app
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
