apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: avelin-api-healthcheck
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portName: http
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: avelin-api
