apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: avelin-api-healthcheck
spec:
  default:
    type: HTTP
    httpHealthCheck:
      requestPath: /health
      portSpecification: USE_SERVING_PORT
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
  targetRef:
    group: ""
    kind: Service
    name: avelin-api
