apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: avelin-web
spec:
  parentRefs:
    - kind: Gateway
      name: avelin-gateway
      namespace: infra
  hostnames:
    - avelin.app
  rules:
    - backendRefs:
        - name: avelin-web
          port: 80
