apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: avelin-web-healthcheck
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 3000
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: avelin-web
