apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: avelin-sync-healthcheck
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_NAMED_PORT
        portName: http
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: avelin-sync
